# Generated by Django 4.1 on 2024-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=200)),
                ('ano_publicacao', models.IntegerField()),
                ('numero_paginas', models.IntegerField()),
                ('capa_id', models.CharField(max_length=50)),
                ('autor', models.ManyToManyField(to='comum.autor', verbose_name='Autores')),
                ('categoria', models.ManyToManyField(to='comum.categoria', verbose_name='Categorias')),
            ],
            options={
                'ordering': ('nome_livro',),
            },
        ),
    ]
